function caption = get_figure_caption(fig_type, n_samples)
% Returns publication-appropriate figure captions.

    if nargin < 2
        n_samples = 0;
    end

    sample_str = '';
    if n_samples > 0
        sample_str = sprintf(' (N=%d)', n_samples);
    end

    switch lower(fig_type)
        case 'tornado'
            caption = sprintf(['Sensitivity analysis of pharmacokinetic parameters on peak concentration (Cmax)%s. ' ...
                'Parameters ranked by absolute Spearman rank correlation coefficient, ' ...
                'with body weight and tumor-related parameters demonstrating strongest influence on inter-individual variability.'], ...
                sample_str);

        case {'distribution', 'outcome_distributions'}
            caption = sprintf(['Distribution of pharmacokinetic outcomes from Monte Carlo Latin hypercube sampling%s. ' ...
                'Left: Peak concentration (Cmax, uM) with clinical toxicity thresholds. ' ...
                'Right: Area under the concentration-time curve (AUC, mg*h/L) with therapeutic window indicated. ' ...
                'Shaded zones represent clinically relevant ranges: green = efficacy target, orange = moderate toxicity risk, red = high toxicity risk.'], ...
                sample_str);

        case 'percentile'
            caption = sprintf(['Percentile distribution analysis of pharmacokinetic exposures%s. ' ...
                'Horizontal lines show 10th, 25th, 50th, 75th, and 90th percentiles; ' ...
                'shaded interquartile range (IQR) encompasses 50%% of patient population. ' ...
                'Red markers indicate minimum and maximum observed values.'], ...
                sample_str);

        case 'cdf'
            caption = sprintf(['Cumulative distribution function plots with clinical target thresholds%s. ' ...
                'Y-axis represents proportion of patients with exposure <= x-axis value. ' ...
                'Vertical lines indicate published therapeutic targets; ' ...
                'steep slope regions indicate tight patient clustering around specific exposure levels.'], ...
                sample_str);

        case {'scatter', 'scatter_cmax', 'scatter_auc'}
            caption = sprintf(['Scatter plots correlating patient covariates with pharmacokinetic exposure%s. ' ...
                'Each point represents one Monte Carlo sample; fitted power-law curve shown with 95%% confidence bands. ' ...
                'R^2 value indicates goodness-of-fit; slopes quantify covariate influence on systemic drug exposure.'], ...
                sample_str);

        case 'statistics'
            caption = sprintf(['Descriptive statistics summary table of pharmacokinetic parameters%s. ' ...
                'Rows: summary statistics (mean, SD, percentiles, clinical percentages); ' ...
                'columns: outcome measures (Cmax, AUC). ' ...
                'Clinical outcomes: percentage of patient population achieving therapeutic efficacy vs. exceeding toxicity thresholds.'], ...
                sample_str);

        otherwise
            caption = sprintf('Figure generated from Monte Carlo pharmacokinetic analysis%s.', sample_str);
    end
end
