function add_figure_metadata(input_csv, n_samples, analysis_date)
% Add metadata annotation showing input file, N, and date.

    metadata_str = sprintf('Input: %s | N=%d sims | %s', input_csv, n_samples, analysis_date);

    annotation('textbox', [0.05, 0.98, 0.9, 0.04], ...
        'String', metadata_str, ...
        'FontSize', 8, ...
        'FontName', 'Arial', ...
        'HorizontalAlignment', 'left', ...
        'VerticalAlignment', 'top', ...
        'EdgeColor', 'none', ...
        'BackgroundColor', [0.95 0.95 0.95], ...
        'FitBoxToText', 'on');
end
